<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>User dropdown in header</description>
   <name>span_UserDropdown</name>
   <tag></tag>
   <elementGuidId>h8i9j0k1-l2m3-n4o5-p6q7-r8s9t0u1v2w3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@class='oxd-userdropdown-tab']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='oxd-topbar-header-userarea']/ul/li</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.oxd-userdropdown-tab</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>m3n4o5p6-q7r8-s9t0-u1v2-w3x4y5z6a7b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oxd-userdropdown-tab</value>
      <webElementGuid>n4o5p6q7-r8s9-t0u1-v2w3-x4y5z6a7b8c9</webElementGuid>
   </webElementProperties>
</WebElementEntity>