<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>User profile dropdown menu in the header</description>
   <name>dropdown_UserProfile</name>
   <tag></tag>
   <elementGuidId>g7890123-ef01-2345-6789-abcdef012345</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@class='oxd-userdropdown-tab']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@class='oxd-userdropdown-tab']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.oxd-userdropdown-tab</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>g7890123-ef01-2345-6789-abcdef012345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oxd-userdropdown-tab</value>
      <webElementGuid>h8901234-f012-3456-789a-bcdef0123456</webElementGuid>
   </webElementProperties>
</WebElementEntity>