<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Password input field on login page</description>
   <name>txt_Password</name>
   <tag></tag>
   <elementGuidId>23456789-bcde-fghi-jklm-2345678901bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@name='password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name='password']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>kkkkkkkk-llll-mmmm-nnnn-oooooooooooo</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>pppppppp-qqqq-rrrr-ssss-tttttttttttt</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>uuuuuuuu-vvvv-wwww-xxxx-yyyyyyyyyyyy</webElementGuid>
   </webElementProperties>
</WebElementEntity>