<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Username input field on login page</description>
   <name>txt_Username</name>
   <tag></tag>
   <elementGuidId>12345678-abcd-efgh-ijkl-1234567890ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@name='username']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name='username']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='username']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>ffffffff-gggg-hhhh-iiii-jjjjjjjjjjjj</webElementGuid>
   </webElementProperties>
</WebElementEntity>