<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Dashboard heading that verifies successful login</description>
   <name>h6_Dashboard</name>
   <tag></tag>
   <elementGuidId>4d5e6f7g-8h9i-0j1k-2l3m-4n5o6p7q8r9s</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//h6[text()='Dashboard']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h6.oxd-text.oxd-text--h6.oxd-topbar-header-breadcrumb-module</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h6[text()='Dashboard']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h6</value>
      <webElementGuid>jjjj1111-kkkk-llll-mmmm-nnnnoooooopp</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dashboard</value>
      <webElementGuid>qqqq1111-rrrr-ssss-tttt-uuuuvvvvwwww</webElementGuid>
   </webElementProperties>
</WebElementEntity>