<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Logout link</description>
   <name>a_Logout</name>
   <tag></tag>
   <elementGuidId>k8l9m0n1-o2p3-q4r5-s6t7-u8v9w0x1y2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[contains(.,'Logout')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Logout')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul.oxd-dropdown-menu > li:last-child > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>q3r4s5t6-u7v8-w9x0-y1z2-a3b4c5d6e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Logout</value>
      <webElementGuid>r4s5t6u7-v8w9-x0y1-z2a3-b4c5d6e7f8</webElementGuid>
   </webElementProperties>
</WebElementEntity>