<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Username input field</description>
   <name>input_Username</name>
   <tag></tag>
   <elementGuidId>b3c4d5e6-f7g8-h9i0-j1k2-l3m4n5o6p7q</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@name='username']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='username']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name='username']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c4d5e6f7-g8h9-i0j1-k2l3-m4n5o6p7q8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>d5e6f7g8-h9i0-j1k2-l3m4-n5o6p7q8r9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Username</value>
      <webElementGuid>e6f7g8h9-i0j1-k2l3-m4n5-o6p7q8r9s0</webElementGuid>
   </webElementProperties>
</WebElementEntity>