<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Username input field on the login page</description>
   <name>input_Username</name>
   <tag></tag>
   <elementGuidId>a1234567-89ab-cdef-0123-456789abcdef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@name='username']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='username']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name='username']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a1234567-89ab-cdef-0123-456789abcdef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>b2345678-9abc-def0-1234-56789abcdef0</webElementGuid>
   </webElementProperties>
</WebElementEntity>