<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Dashboard header after successful login</description>
   <name>header_Dashboard</name>
   <tag></tag>
   <elementGuidId>6789abcd-efgh-ijkl-mnop-6789012ghijk</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//h6[text()='Dashboard']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h6.oxd-text.oxd-text--h6.oxd-topbar-header-breadcrumb-module</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h6[contains(.,'Dashboard')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h6</value>
      <webElementGuid>cccccccc-dddd-eeee-ffff-333333333333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dashboard</value>
      <webElementGuid>dddddddd-eeee-ffff-gggg-444444444444</webElementGuid>
   </webElementProperties>
</WebElementEntity>