<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Login button</description>
   <name>button_Login</name>
   <tag></tag>
   <elementGuidId>c3d4e5f6-g7h8-9i01-j2k3-l4m5n6o78901</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.oxd-button.oxd-button--medium.oxd-button--main.orangehrm-login-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f6g7h8i9-j0k1-l2m3-n4o5-p6q7r8s9t0u1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>g7h8i9j0-k1l2-m3n4-o5p6-q7r8s9t0u1v2</webElementGuid>
   </webElementProperties>
</WebElementEntity>