<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Username input field on login page</description>
   <name>input_Username</name>
   <tag></tag>
   <elementGuidId>a1b2c3d4-e5f6-7890-a1b2-c3d4e5f67890</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@name='username']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='username']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name='username']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b2c3d4e5-f6a7-8b9c-0d1e-2f3a4b5c6d7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>c3d4e5f6-a7b8-9c0d-1e2f-3a4b5c6d7e8f</webElementGuid>
   </webElementProperties>
</WebElementEntity>