<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Login button on login page</description>
   <name>button_Login</name>
   <tag></tag>
   <elementGuidId>c3d4e5f6-g7h8-9012-cdef-g3h4i5j6k7l8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[type='submit']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[contains(@class, 'orangehrm-login-button') and @type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>g7h8i9j0-1234-56fg-hijk-m7n8o9p0q1r2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>h8i9j0k1-2345-67gh-ijkl-n8o9p0q1r2s3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>contains</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>orangehrm-login-button</value>
      <webElementGuid>i9j0k1l2-3456-78hi-jklm-o9p0q1r2s3t4</webElementGuid>
   </webElementProperties>
</WebElementEntity>