<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Dashboard header text element</description>
   <name>h6_Dashboard</name>
   <tag></tag>
   <elementGuidId>d4e5f6g7-h8i9-0123-defg-h4i5j6k7l8m9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//h6[text()='Dashboard']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h6.oxd-text.oxd-text--h6.oxd-topbar-header-breadcrumb-module</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h6[contains(@class, 'oxd-topbar-header-breadcrumb-module')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h6</value>
      <webElementGuid>j0k1l2m3-4567-89ij-klmn-p0q1r2s3t4u5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>contains</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oxd-topbar-header-breadcrumb-module</value>
      <webElementGuid>k1l2m3n4-5678-90jk-lmno-q1r2s3t4u5v6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dashboard</value>
      <webElementGuid>l2m3n4o5-6789-01kl-mnop-r2s3t4u5v6w7</webElementGuid>
   </webElementProperties>
</WebElementEntity>