<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>User dropdown menu in top right corner</description>
   <name>span_User_Dropdown</name>
   <tag></tag>
   <elementGuidId>e5f6g7h8-i9j0-1234-efgh-i5j6k7l8m9n0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@class='oxd-userdropdown-tab']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.oxd-userdropdown-tab</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='oxd-topbar-header-userarea']/ul/li/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>m3n4o5p6-7890-12lm-nopq-s3t4u5v6w7x8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oxd-userdropdown-tab</value>
      <webElementGuid>n4o5p6q7-8901-23mn-opqr-t4u5v6w7x8y9</webElementGuid>
   </webElementProperties>
</WebElementEntity>