<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Logout link in user menu dropdown</description>
   <name>link_Logout</name>
   <tag></tag>
   <elementGuidId>67890123-fghi-6789-jklm-67890123abcd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[contains(text(),'Logout')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.oxd-userdropdown-link:contains('Logout')</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Logout')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>12345678-1234-5678-1234-567890abcdef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Logout</value>
      <webElementGuid>23456789-2345-6789-2345-6789abcdefgh</webElementGuid>
   </webElementProperties>
</WebElementEntity>