<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Username input field on login page</description>
   <name>input_Username</name>
   <tag></tag>
   <elementGuidId>1a2b3c4d-5e6f-7g8h-9i0j-1k2l3m4n5o6p</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@name='username']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name='username']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='username']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>abcd1234-ef56-7890-abcd-ef1234567890</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>11223344-5566-7788-9900-112233445566</webElementGuid>
   </webElementProperties>
</WebElementEntity>