<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Login button</description>
   <name>button_Login</name>
   <tag></tag>
   <elementGuidId>d1e2f3g4-h5i6-j7k8-l9m0-n1o2p3q4r5s6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.oxd-button.oxd-button--medium.oxd-button--main.orangehrm-login-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>abcdef12-3456-7890-abcd-ef1234567890</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>abcdef12-3456-7890-abcd-ef1234567890</webElementGuid>
   </webElementProperties>
</WebElementEntity>