<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Username input field on login page</description>
   <name>input_Username</name>
   <tag></tag>
   <elementGuidId>b1c2d3e4-f5g6-h7i8-j9k0-l1m2n3o4p5q6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@name='username']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='username']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name='username']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>54321abc-def9-8765-4321-fedcba987654</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>54321abc-def9-8765-4321-fedcba987654</webElementGuid>
   </webElementProperties>
</WebElementEntity>