<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>User profile dropdown in the top menu</description>
   <name>dropdown_UserMenu</name>
   <tag></tag>
   <elementGuidId>789abcde-fghi-jklm-nopq-789012hijklm</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@class='oxd-userdropdown-tab']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.oxd-userdropdown-tab</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='oxd-topbar-header-userarea']/ul/li/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>eeeeeeee-ffff-gggg-hhhh-555555555555</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oxd-userdropdown-tab</value>
      <webElementGuid>ffffffff-gggg-hhhh-iiii-666666666666</webElementGuid>
   </webElementProperties>
</WebElementEntity>