<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Reset Password button</description>
   <name>btn_ResetPassword</name>
   <tag></tag>
   <elementGuidId>9abcdefg-hijk-lmno-pqrs-9012jklmnopq</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.oxd-button.oxd-button--medium.oxd-button--secondary.orangehrm-forgot-password-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>iiiiiiii-jjjj-kkkk-llll-999999999999</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>jjjjjjjj-kkkk-llll-mmmm-aaaaaaaaaaaa</webElementGuid>
   </webElementProperties>
</WebElementEntity>